### ISSUE TITLE
Handling Birthday Data

### ISSUE THREAD

**Issue by xyzhg** [mokumoku-lovers/moku-moku-users#30]
Currently, `Save()` in DAO does nothing with `user.Birthday` since we may not need our users to give their birthday info during the registration process, but `Update()` function should somehow consider about it because user may add their bitday info later.

(Indeed, `Save()` may need also do something with the birthday data from the back-end point of view. If birthday info is not necessary, then front-end can just transfer an empty value.)

However, while `Update()` handling the birthday data, there is a problem:
Currently, `user.Birthday` for illegal or empty value is parsed to `"0001-01-01"` instead of `nil` since a string-type-defined variable `user.Birthday` cannot be `nil` but this might not be the best solution. Therefore, we may need to decide how to handle with the illegal or empty `user.Birthday` value — just store `"0001-01-01"` in the database or store `null` by somehow changing the `user.Birthday` value to `nil`.

**Comment by JiahuiChen99** [comment]
In `Create User` endpoint we're inserting a nil because there's no Birthday field in the registration form.
For `Update User` endpoint we could check if birthday is an empty string, if that's the case, then we execute the query with **birthday** as **nil**. Otherwise, we conver the birthday string convert it to time and execute the query with that data 👀
